name: Package and Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # we need the last two commits to check if the version changed
        
      - name: Get package version
        id: check_versions
        run: |
          $previous_version = git show HEAD~1:release/app/package.json | Select-String -Pattern '"version":' | ForEach-Object { $_ -replace '.*?: "(.*)",', '$1' }
          $current_version = git show HEAD:release/app/package.json | Select-String -Pattern '"version":' | ForEach-Object { $_ -replace '.*?: "(.*)",', '$1' }

          "previous_version=$previous_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "current_version=$current_version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          if ($previous_version -ne $current_version) {
            "version_changed=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "version_changed=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

          "Previous Version = $previous_version, Current Version = $current_version" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: D2RMM ${{ steps.check_versions.outputs.current_version }}.zip
          path: release/build/D2RMM ${{ steps.check_versions.outputs.current_version }}.zip

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: D2RMM ${{ steps.check_versions.outputs.current_version }}
          tag: v${{ steps.check_versions.outputs.current_version }}
          allowUpdates: true
          prerelease: true
          omitPrereleaseDuringUpdate: true
          artifacts: release/build/D2RMM ${{ steps.check_versions.outputs.current_version }}.zip
          replacesArtifacts: true
          generateReleaseNotes: true

      - name: Finalize pre-release
        if: steps.check_versions.outputs.version_changed == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const previousVersion = "${{ steps.check_versions.outputs.previous_version }}";
            const releaseToUpdate = releases.find(release => release.tag_name === `v${previousVersion}`);
            if (releaseToUpdate) {
              await github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: releaseToUpdate.id,
                tag_name: releaseToUpdate.tag_name,
                prerelease: false
              });
            }
